---
name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: super-linter/super-linter/slim@v7
        env:
          GITHUB_TOKEN: ${{ github.token }}
          # terrascan throws when you use variables in a bunch of places and it seems redundant
          VALIDATE_TERRAFORM_TERRASCAN: false
