---
name: Tracker Docker Image
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      force:
        description: 'Force a new build?'
        required: true
        default: false
        type: boolean

permissions:
  packages: write

env:
  IMAGE_NAME: "ghcr.io/${{ github.repository }}"

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      should-build: ${{ steps.check.outputs.should-build }}
    steps:
      - uses: actions/checkout@v4
        id: checkout
        with:
          repository: GoBLFC/Tracker
          ref: main
      - id: check
        run: |
          PACKAGE_NAME="$(echo "${{ github.repository }}-app" | cut -d '/' -f 2)"
          SHOULD_BUILD="$(gh api "/user/packages/container/$PACKAGE_NAME/versions" | \
            jq '[.[] | select(.metadata.container.tags | index("latest"))] | length == 0' \
            || echo 'true')"
          echo "should-build=$SHOULD_BUILD" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ inputs.force || needs.check.outputs.should-build == 'true' }}
    strategy:
      matrix:
        image:
          - app
          - nginx
    steps:
      - uses: actions/checkout@v4
        id: checkout
        with:
          repository: GoBLFC/Tracker
          ref: main
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: .docker/Dockerfile-${{ matrix.image }}
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: "${{ env.IMAGE_NAME }}-${{ matrix.image }}:${{ steps.checkout.outputs.commit }},${{ env.IMAGE_NAME }}-${{ matrix.image }}:latest"
