---
name: Tracker Docker Image
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        id: checkout
        with:
          repository: GoBLFC/Tracker
          ref: main
      # TODO: publish at least one build first so we can debug this
      # - name: check if release exists
      #   run: |
      #     gh api "/user/packages/container/goblfc-tracker/versions/${{ steps.checkout.outputs.commit }}"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: .docker/Dockerfile-app
          platforms: linux/arm64
          push: true
          tags: "${{ github.repository }}:${{ steps.checkout.outputs.commit }},${{ github.repository }}:latest"
