---
name: Tracker Docker Image
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  packages: write

env:
  IMAGE_NAME: "ghcr.io/${{ github.repository }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        id: checkout
        with:
          repository: GoBLFC/Tracker
          ref: main
      - id: check
        run: |
          PACKAGE_NAME="$(echo "${{ github.repository }}" | cut -d '/' -f 2)"
          SHOULD_BUILD="$(gh api "/user/packages/container/$PACKAGE_NAME/versions" | \
            jq '[.[] | select(.metadata.container.tags | index("latest"))] | length == 0')"
          echo "should-build=$SHOULD_BUILD" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
        if: ${{ steps.check.outputs.should-build == 'true' }}
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v3
        if: ${{ steps.check.outputs.should-build == 'true' }}
      - uses: docker/login-action@v3
        if: ${{ steps.check.outputs.should-build == 'true' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v6
        if: ${{ steps.check.outputs.should-build == 'true' }}
        with:
          context: .
          file: .docker/Dockerfile-app
          platforms: linux/arm64
          push: true
          tags: "${{ env.IMAGE_NAME }}:${{ steps.checkout.outputs.commit }},${{ env.IMAGE_NAME }}:latest"
